### ISSUE TITLE
記事ごとのディレクトリ配下にいれた画像のパスがおかしくなる

### ISSUE THREAD

**Issue by tarky** [ngs/middleman-blog-similar#13]
おかげさまで似ている記事の一覧は表示することができました。ただ、記事内のimgタグのsrc属性のパスがおかしくなってしまいます。

当方記事のファイルは

`/source/articles/2016-07/07-make-kattene/index.html.md`

のようなパスに配置しています。画像は、

`/source/articles/2016-07/07-make-kattene/images/one-pc.png`

というようなパスで管理しています。

記事内にてMarkdownで、（Kramdownを使用しています）

``` markdown
![ホゲホゲ](images/one-pc.png)
```

というように書くと、通常

``` html
<img alt="ホゲホゲ" src="/articles/2016-07/07-make-kattene/images/one-pc.png">
```

というように出力してくれます。

ですが、本gemを導入したところ、middleman serverを起動し、一発目にアクセスした記事は上記のように正しく出力されるのですが、違う記事をクリックして表示すると画像のパスが

``` html
<img alt="ホゲホゲ" src="/images/images/one-pc.png">
```

のようになってしまいます。一発目にアクセスした記事以外の記事の画像は全てこうなってしまい、画像が表示されなくなってしまいます。

pryなどで色々と調べたところ、
kramdownはimgタグを出力する際、image_tag()を内部的に使っているようですが、その中でcurrent_resourceを使ってパスを生成しています。

middleman-blog-similarでは、development環境時、一発目にアクセスした際に全ての記事をレンダーして解析し、その全記事情報をキャッシュに入れているようにお見受けします。その際に、各記事をレンダーする時に呼び出されるcurrent_resourceは、それぞれの記事ではなく、一発目にアクセスしている記事を参照してしまっているのが原因のようです。なので、間違った画像のパスを生成し、sitemap内でそのパスで検索する処理でそのようなresourceがないので、全て`/images`というのを頭につけてしまい、上記のようなパスになるようです。

build時は全ての記事で

``` html
<img alt="ホゲホゲ" src="/images/images/one-pc.png">
```

というようなパスになってしまいます。おそらく全ての記事でcurrent_resourceがnilになるからだと思います。

使っているのは下のバージョンです。

| gem | version |
| --- | --- |
| middleman-core | 3.4.0 |
| middleman-blog | 3.6.0 |
| middleman-blog-similar | 1.1.1 |
| kramdown | 1.9.0 |

使っているアルゴリズムは`:'word_frequency/mecab'`です。

こちらの手落ちの可能性もありますが、どうかご対応、または対処策を教えていただけたら幸いです。

**Comment by ngs** [comment]
返信遅れて申し訳ありません。 #15 で 2.0.0 としてリファクタリングしました。
このバージョンを使って再現するようでしたら、Re-open お願いいたします。
