### ISSUE TITLE
stack level too deep on evaluating similar_articles of a blog article

### ISSUE THREAD

**Issue by saravanak** [ngs/middleman-blog-similar#9]
I have two blog articles in the default blog path. When I try to use the extension, I get a `stack level too deep` error. 
## Steps to replicate

To replicate, clone [this](https://github.com/saravanak/blog_similar_issue) repo under `~/.middleman`. 

Then initialize a new middleman project based on the above template:

``` sh
middleman init --template=blog_similar_issue
bundler install --local
middleman server --verbose
```

Then access `localhost:4567` in the browser, You should see the following message on the console:

``` sh
[2015-06-11 11:47:21] ERROR SystemStackError: stack level too deep
    /Users/x/.rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/front_matter.rb:212
```

**Comment by ngs** [comment]
Refactored in #15 , This may not reproduce, please re-open if you see this error again. Thanks.
